// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NettruyenRemake.Models;

#nullable disable

namespace NettruyenRemake.Migrations
{
    [DbContext(typeof(NettruyenDbContext))]
    [Migration("20250330125844_AddCreatedByToComics")]
    partial class AddCreatedByToComics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComicCategory", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("ComicId", "CategoryId")
                        .HasName("PK__comic_ca__F68F10FB4EEDA496");

                    b.HasIndex("CategoryId");

                    b.ToTable("comic_category", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("PK__categori__D54EE9B421EFB9E4");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__categori__5189E25597502E73")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("BackupContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("backup_content");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int")
                        .HasColumnName("chapter_number");

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("ChapterId")
                        .HasName("PK__chapters__745EFE876D8C779E");

                    b.HasIndex("ComicId");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.ChapterComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__chapter___E7957687BD252489");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId");

                    b.ToTable("chapter_comments", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Comic", b =>
                {
                    b.Property<int>("ComicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComicId"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("author");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ComicId")
                        .HasName("PK__comics__ABDBFE60FF467A05");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StatusId");

                    b.ToTable("comics", null, t =>
                        {
                            t.HasTrigger("trg_InsertComicStats");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__comic_co__E7957687CD8E560C");

                    b.HasIndex("ComicId");

                    b.HasIndex("UserId");

                    b.ToTable("comic_comments", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicStat", b =>
                {
                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<int?>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("comment_count");

                    b.Property<int?>("FollowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("follow_count");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("ComicId")
                        .HasName("PK__comic_st__ABDBFE604578B1F1");

                    b.ToTable("comic_stats", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__comic_st__3683B531FAC5C254");

                    b.HasIndex(new[] { "StatusName" }, "UQ__comic_st__501B3753407643E2")
                        .IsUnique();

                    b.ToTable("comic_status", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Follow", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("follow_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowId"));

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<DateTime?>("FollowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("followed_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("FollowId")
                        .HasName("PK__follows__15A691442D150A99");

                    b.HasIndex("ComicId");

                    b.HasIndex("UserId");

                    b.ToTable("follows", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("RatingValue")
                        .HasColumnType("int")
                        .HasColumnName("rating_value");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RatingId")
                        .HasName("PK__ratings__D35B278B2B187778");

                    b.HasIndex("ComicId");

                    b.HasIndex("UserId");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.ReadingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    b.Property<int>("ComicId")
                        .HasColumnType("int")
                        .HasColumnName("comic_id");

                    b.Property<DateTime?>("LastReadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("last_read_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId")
                        .HasName("PK__reading___096AA2E973137E58");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ComicId");

                    b.HasIndex("UserId");

                    b.ToTable("reading_history", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__roles__760965CC7012BDD9");

                    b.HasIndex(new[] { "RoleName" }, "UQ__roles__783254B12AB7A719")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NettruyenRemake.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F0C60C439");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164200BB995")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__users__F3DBC5728565DA79")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ComicCategory", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__comic_cat__categ__5EBF139D");

                    b.HasOne("NettruyenRemake.Models.Comic", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__comic_cat__comic__5DCAEF64");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Chapter", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithMany("Chapters")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__chapters__comic___5812160E");

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("NettruyenRemake.Models.ChapterComment", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Chapter", "Chapter")
                        .WithMany("ChapterComments")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__chapter_c__chapt__68487DD7");

                    b.HasOne("NettruyenRemake.Models.User", "User")
                        .WithMany("ChapterComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__chapter_c__user___6754599E");

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Comic", b =>
                {
                    b.HasOne("NettruyenRemake.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_comics_users_created_by");

                    b.HasOne("NettruyenRemake.Models.ComicStatus", "Status")
                        .WithMany("Comics")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__comics__status_i__46E78A0C");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicComment", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithMany("ComicComments")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__comic_com__comic__6383C8BA");

                    b.HasOne("NettruyenRemake.Models.User", "User")
                        .WithMany("ComicComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__comic_com__user___628FA481");

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicStat", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithOne("ComicStat")
                        .HasForeignKey("NettruyenRemake.Models.ComicStat", "ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__comic_sta__comic__4E88ABD4");

                    b.Navigation("Comic");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Follow", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithMany("Follows")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__follows__comic_i__5441852A");

                    b.HasOne("NettruyenRemake.Models.User", "User")
                        .WithMany("Follows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__follows__user_id__534D60F1");

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Rating", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithMany("Ratings")
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ratings__comic_i__6E01572D");

                    b.HasOne("NettruyenRemake.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ratings__user_id__6D0D32F4");

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NettruyenRemake.Models.ReadingHistory", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Chapter", "Chapter")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__reading_h__chapt__73BA3083");

                    b.HasOne("NettruyenRemake.Models.Comic", "Comic")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("ComicId")
                        .IsRequired()
                        .HasConstraintName("FK__reading_h__comic__72C60C4A");

                    b.HasOne("NettruyenRemake.Models.User", "User")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__reading_h__user___71D1E811");

                    b.Navigation("Chapter");

                    b.Navigation("Comic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NettruyenRemake.Models.User", b =>
                {
                    b.HasOne("NettruyenRemake.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__users__role_id__3E52440B");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Chapter", b =>
                {
                    b.Navigation("ChapterComments");

                    b.Navigation("ReadingHistories");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Comic", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ComicComments");

                    b.Navigation("ComicStat");

                    b.Navigation("Follows");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingHistories");
                });

            modelBuilder.Entity("NettruyenRemake.Models.ComicStatus", b =>
                {
                    b.Navigation("Comics");
                });

            modelBuilder.Entity("NettruyenRemake.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NettruyenRemake.Models.User", b =>
                {
                    b.Navigation("ChapterComments");

                    b.Navigation("ComicComments");

                    b.Navigation("Follows");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
